{% set name = "bcolz-zipline" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bcolz_zipline-{{ version }}.tar.gz
  sha256: e4da689704593eafd48f0ad57df62cf5a59c6643f180c9cbddc35d4bd35b6aa7

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - toml
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  commands:
    - python -c "import bcolz; bcolz.test()"
  requires:
    - numpy
    - setuptools

about:
  home: https://pypi.org/project/bcolz-zipline/
  summary: Columnar and compressed data containers.
  license: BSD-3-Clause
  license_file: LICENSES/BCOLZ.txt

extra:
  recipe-maintainers:
    - stefan-jansen
