{% set name = "bcolz-zipline" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bcolz_zipline-{{ version }}.tar.gz
  sha256: 51166ad88e20ba70af7677b9402ffdecfe327ed4d0d15d59a9c249323bf11433

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - toml
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - packaging

test:
  commands:
    - python -c "import bcolz; bcolz.test()"
  requires:
    - numpy
    - setuptools

about:
  home: https://pypi.org/project/bcolz-zipline/
  summary: Columnar and compressed data containers.
  license: BSD-3-Clause
  license_file: LICENSES/BCOLZ.txt

extra:
  recipe-maintainers:
    - stefan-jansen
